// Package httphandler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package httphandler

// CreatedResponse defines model for CreatedResponse.
type CreatedResponse struct {
	Message string `json:"message"`
}

// PostDisburseRequest defines model for PostDisburseRequest.
type PostDisburseRequest struct {
	Amount float32 `json:"amount"`
}

// PostDisburseBody defines model for PostDisburseBody.
type PostDisburseBody = PostDisburseRequest

// DisburseJSONRequestBody defines body for Disburse for application/json ContentType.
type DisburseJSONRequestBody = PostDisburseRequest
